#!/usr/bin/env python3
"""一次性入库：2026-10-07 第十轮（GeoNode 画廊存量复测 + 专题纵深）新增 18 条。

实测证据（2026-10-07，全部本轮真实请求）：
- GeoNode 画廊 9 家：GetCapabilities 均返回 WMS_Capabilities，strong
  （atlas.thuenen.de / cedoc / dominode.dm 等 6 家是前几轮记录"本机超时"的，本轮复测复活）
- 专题 9 家：NT 地质 / BGS 1:50k / FEMA GeoServer / NOAA NCEP(940 图层) / BOM THREDDS strong；
  3 家 NOAA·IOOS ERDDAP search API 应答规范协议头但全文检索返回空，按 weak 收，notes 写明
未收录（单次失败不硬凑，留待下轮复测）：pacioos(ows 404)、CropScape(Tomcat 报错)、
OneGeology BRGM(空响应)、droughtmonitor(WMS 路径 404)、landscapeportal(仅首页，无接口证据不收)、
NH GRANIT(403 反爬)、adc.met.no / socib THREDDS(超时)、dominode.dm(502)、INTA(超时)等
"""
import sqlite3
import sys

if sys.platform == "win32":
    sys.stdout.reconfigure(encoding="utf-8")

TODAY = "2026-10-07"

W = "OGC WMS"

NEW_ROWS = [
    # ---------- GeoNode 画廊存量复测强命中 ----------
    dict(
        service_id="R10-0001", service_name="CNR ISMAR Cigno GeoServer WMS",
        country="意大利", region="欧洲", provider="CNR ISMAR（意大利海洋科学研究所）",
        category="海洋", service_type="WMS", protocol=W,
        official_url="https://cigno.ve.ismar.cnr.it/", service_url="https://cigno.ve.ismar.cnr.it/geoserver/wms?service=WMS&request=GetCapabilities",
        docs_url="None", layer_or_endpoint="geoserver/wms（126 图层）",
        data_description="意大利国家研究委员会海洋科学研究所(CNR ISMAR，威尼斯分部)的 Cigno GeoServer：亚得里亚海/潟湖海洋观测与制图图层",
        spatial_coverage="地中海北部/亚得里亚海", temporal_coverage="静态与持续更新",
        crs="CRS:84;AUTO:42001-42004", resolution="未标注", update_frequency="未知",
        format="PNG;GeoTIFF", auth="无", api_key_required="否", registration_required="否",
        free="是", commercial_use="未知", redistribution="未知", attribution="CNR ISMAR",
        need_no_reg="是", need_no_key="是", is_free="是",
        support_api="是", support_spatial_query="未知", support_temporal_query="未知",
        support_batch="未知", support_download="未知", support_geojson="否", support_json="否",
        is_vector="是", is_raster="是", is_realtime="否",
        global_coverage="否", region_coverage="是",
        status="已验证", verify_method="protocol-probe:strong", last_verified=TODAY,
        notes="GetCapabilities 返回 WMS_Capabilities(2026-10-07)，126 个命名图层；服务标题仍是默认'My GeoServer WMS'，元数据以图层清单为准",
    ),
    dict(
        service_id="R10-0002", service_name="Thünen Atlas WMS（德国联邦农业农村林业研究所）",
        country="德国", region="欧洲", provider="Thünen-Institut（Johann Heinrich von Thünen 研究所）",
        category="农业/农村经济", service_type="WMS", protocol=W,
        official_url="https://atlas.thuenen.de/", service_url="https://atlas.thuenen.de/geoserver/wms?service=WMS&request=GetCapabilities",
        docs_url="https://atlas.thuenen.de/", layer_or_endpoint="geoserver/wms（560 图层）",
        data_description="德国联邦粮食林业研究所(Thünen)在线地图集：林业清查、农业结构、农村空间监测、土壤与气候专题图层",
        spatial_coverage="德国", temporal_coverage="多年清查",
        crs="EPSG:25832;EPSG:25833;EPSG:3035;EPSG:31467", resolution="未标注", update_frequency="未知",
        format="PNG;GeoTIFF", auth="无", api_key_required="否", registration_required="否",
        free="是", commercial_use="未知", redistribution="未知", attribution="Thünen-Institut",
        need_no_reg="是", need_no_key="是", is_free="是",
        support_api="是", support_spatial_query="未知", support_temporal_query="未知",
        support_batch="未知", support_download="未知", support_geojson="否", support_json="否",
        is_vector="是", is_raster="是", is_realtime="否",
        global_coverage="否", region_coverage="是",
        status="已验证", verify_method="protocol-probe:strong", last_verified=TODAY,
        notes="GetCapabilities 返回 WMS_Capabilities(2026-10-07)，560 个图层；本地坐标系 EPSG:25832/31467，作全国底图需注意投影",
    ),
    dict(
        service_id="R10-0003", service_name="Sardegna CEDOC 区域制图 GeoServer WMS",
        country="意大利", region="欧洲", provider="Regione Sardegna（撒丁大区）",
        category="测绘", service_type="WMS", protocol=W,
        official_url="https://cedoc-webgis.regione.sardegna.it/", service_url="https://cedoc-webgis.regione.sardegna.it/geoserver/wms?service=WMS&request=GetCapabilities",
        docs_url="None", layer_or_endpoint="geoserver/wms（125 图层）",
        data_description="撒丁大区 CEDOC 数字制图目录 GeoServer：区域地形图、航空影像、地籍与规划图层",
        spatial_coverage="意大利撒丁岛", temporal_coverage="静态与持续更新",
        crs="EPSG:3003;EPSG:32632;CRS:84", resolution="未标注", update_frequency="未知",
        format="PNG;GeoTIFF", auth="无", api_key_required="否", registration_required="否",
        free="是", commercial_use="未知", redistribution="未知", attribution="Regione Sardegna",
        need_no_reg="是", need_no_key="是", is_free="是",
        support_api="是", support_spatial_query="未知", support_temporal_query="未知",
        support_batch="未知", support_download="未知", support_geojson="否", support_json="否",
        is_vector="是", is_raster="是", is_realtime="否",
        global_coverage="否", region_coverage="是",
        status="已验证", verify_method="protocol-probe:strong", last_verified=TODAY,
        notes="GetCapabilities 返回 WMS_Capabilities(2026-10-07)；EPSG:3003 为意大利老 Gauss-Boaga 投影",
    ),
    dict(
        service_id="R10-0004", service_name="FrameFAVN GeoServer WMS（身份待确认）",
        country="越南", region="亚洲", provider="未知（FrameFAVN）",
        category="综合/政府开放数据", service_type="WMS", protocol=W,
        official_url="https://framefavn.org/", service_url="https://framefavn.org/geoserver/wms?service=WMS&request=GetCapabilities",
        docs_url="None", layer_or_endpoint="geoserver/wms（72 图层）",
        data_description="疑似 frame-vn.org 同系的 GeoNode/GeoServer 实例：72 个专题图层；国别依据坐标系(EPSG:32647/32648)与域名推断",
        spatial_coverage="东南亚（据 CRS 推断）", temporal_coverage="未知",
        crs="EPSG:32647;EPSG:32648;EPSG:3405;CRS:84", resolution="未标注", update_frequency="未知",
        format="PNG", auth="无", api_key_required="否", registration_required="否",
        free="是", commercial_use="未知", redistribution="未知", attribution="未知",
        need_no_reg="是", need_no_key="是", is_free="是",
        support_api="是", support_spatial_query="未知", support_temporal_query="未知",
        support_batch="未知", support_download="未知", support_geojson="否", support_json="否",
        is_vector="是", is_raster="是", is_realtime="否",
        global_coverage="否", region_coverage="是",
        status="已验证", verify_method="protocol-probe:strong", last_verified=TODAY,
        notes="GetCapabilities 返回 WMS_Capabilities(2026-10-07) 是事实；但域名疑似 frame-vn.org 的变体克隆、服务标题为默认值，运营方身份未确认，使用前建议人工核一层",
    ),
    dict(
        service_id="R10-0005", service_name="阿根廷 Cuyo 大区 GeoPortal GeoServer WMS",
        country="阿根廷", region="南美", provider="IDERA / Región de Cuyo",
        category="综合/政府开放数据", service_type="WMS", protocol=W,
        official_url="https://geoportal.lujandecuyo.gob.ar/", service_url="https://geoportal.lujandecuyo.gob.ar/geoserver/wms?service=WMS&request=GetCapabilities",
        docs_url="None", layer_or_endpoint="geoserver/wms（48 图层）",
        data_description="阿根廷库约大区(门多萨/圣胡安/圣路易斯)空间数据基础设施(IDERA)节点：行政区划、水文、灾害与基础地理图层",
        spatial_coverage="阿根廷库约大区", temporal_coverage="未知",
        crs="EPSG:22172;EPSG:22182;CRS:84", resolution="未标注", update_frequency="未知",
        format="PNG", auth="无", api_key_required="否", registration_required="否",
        free="是", commercial_use="未知", redistribution="未知", attribution="IDERA Cuyo",
        need_no_reg="是", need_no_key="是", is_free="是",
        support_api="是", support_spatial_query="未知", support_temporal_query="未知",
        support_batch="未知", support_download="未知", support_geojson="否", support_json="否",
        is_vector="是", is_raster="是", is_realtime="否",
        global_coverage="否", region_coverage="是",
        status="已验证", verify_method="protocol-probe:strong", last_verified=TODAY,
        notes="GetCapabilities 返回 WMS_Capabilities(2026-10-07)；EPSG:22172/22182 为阿根廷高斯-克吕格分带",
    ),
    dict(
        service_id="R10-0006", service_name="阿根廷公共工程部 GeoServer WMS",
        country="阿根廷", region="南美", provider="Ministerio de Obras Públicas（阿根廷公共工程部）",
        category="综合/政府开放数据", service_type="WMS", protocol=W,
        official_url="https://geoportal.obraspublicas.gob.ar/", service_url="https://geoportal.obraspublicas.gob.ar/geoserver/wms?service=WMS&request=GetCapabilities",
        docs_url="None", layer_or_endpoint="geoserver/wms（284 图层）",
        data_description="阿根廷公共工程部地理门户 GeoServer：全国基础设施、道路、水利、工程招标与基础地理图层（284 个）",
        spatial_coverage="阿根廷全国", temporal_coverage="持续更新",
        crs="EPSG:22183;EPSG:3857;EPSG:4326", resolution="未标注", update_frequency="未知",
        format="PNG", auth="无", api_key_required="否", registration_required="否",
        free="是", commercial_use="未知", redistribution="未知", attribution="MOP Argentina",
        need_no_reg="是", need_no_key="是", is_free="是",
        support_api="是", support_spatial_query="未知", support_temporal_query="未知",
        support_batch="未知", support_download="未知", support_geojson="否", support_json="否",
        is_vector="是", is_raster="是", is_realtime="否",
        global_coverage="否", region_coverage="是",
        status="已验证", verify_method="protocol-probe:strong", last_verified=TODAY,
        notes="GetCapabilities 返回 WMS_Capabilities(2026-10-07)，服务标题'Ministerio de Obras Públicas'，284 图层",
    ),
    dict(
        service_id="R10-0007", service_name="INFO/RAC KMAP 地中海环境知识地图 WMS",
        country="国际组织", region="全球", provider="INFO/RAC（UNEP/MAP 巴塞罗那公约区域活动中心）",
        category="海洋", service_type="WMS", protocol=W,
        official_url="https://kmap.info-rac.org/", service_url="https://kmap.info-rac.org/geoserver/wms?service=WMS&request=GetCapabilities",
        docs_url="None", layer_or_endpoint="geoserver/wms（42 图层）",
        data_description="联合国环境署地中海行动计划(UNEP/MAP)信息中心的知识地图平台：地中海海洋环境、污染、生物多样性与沿岸带专题图层",
        spatial_coverage="地中海区域", temporal_coverage="未知",
        crs="EPSG:3035;CRS:84", resolution="未标注", update_frequency="未知",
        format="PNG", auth="无", api_key_required="否", registration_required="否",
        free="是", commercial_use="未知", redistribution="未知", attribution="INFO/RAC UNEP/MAP",
        need_no_reg="是", need_no_key="是", is_free="是",
        support_api="是", support_spatial_query="未知", support_temporal_query="未知",
        support_batch="未知", support_download="未知", support_geojson="否", support_json="否",
        is_vector="是", is_raster="是", is_realtime="否",
        global_coverage="否", region_coverage="是",
        status="已验证", verify_method="protocol-probe:strong", last_verified=TODAY,
        notes="GetCapabilities 返回 WMS_Capabilities(2026-10-07)，42 图层",
    ),
    dict(
        service_id="R10-0008", service_name="UNEP/GRID 可持续高加索 GeoNode WMS",
        country="国际组织", region="欧洲/亚洲", provider="UNEP/GRID- Geneva（环境署 GRID）",
        category="环境", service_type="WMS", protocol=W,
        official_url="https://sustainable-caucasus.unepgrid.ch/", service_url="https://sustainable-caucasus.unepgrid.ch/geoserver/wms?service=WMS&request=GetCapabilities",
        docs_url="None", layer_or_endpoint="geoserver/wms（98 图层）",
        data_description="联合国环境署 GRID 的高加索可持续发展平台：亚美尼亚/阿塞拜疆/格鲁吉亚土地利用、森林、水与保护区图层",
        spatial_coverage="高加索三国", temporal_coverage="未知",
        crs="EPSG:28408;EPSG:3035;CRS:84", resolution="未标注", update_frequency="未知",
        format="PNG", auth="无", api_key_required="否", registration_required="否",
        free="是", commercial_use="未知", redistribution="未知", attribution="UNEP/GRID",
        need_no_reg="是", need_no_key="是", is_free="是",
        support_api="是", support_spatial_query="未知", support_temporal_query="未知",
        support_batch="未知", support_download="未知", support_geojson="否", support_json="否",
        is_vector="是", is_raster="是", is_realtime="否",
        global_coverage="否", region_coverage="是",
        status="已验证", verify_method="protocol-probe:strong", last_verified=TODAY,
        notes="GetCapabilities 返回 WMS_Capabilities(2026-10-07)，98 图层",
    ),
    dict(
        service_id="R10-0009", service_name="波河流域管理局 AdB Po WebGIS WMS",
        country="意大利", region="欧洲", provider="Autorità di Bacino Distrettuale del Fiume Po",
        category="水文", service_type="WMS", protocol=W,
        official_url="https://webgis.adbpo.it/", service_url="https://webgis.adbpo.it/geoserver/wms?service=WMS&request=GetCapabilities",
        docs_url="None", layer_or_endpoint="geoserver/wms（769 图层）",
        data_description="意大利波河流域特区管理局官方 WebGIS：流域水文、洪水风险区、水监测网、地形与规划图层，769 个命名图层",
        spatial_coverage="意大利波河流域", temporal_coverage="持续更新",
        crs="EPSG:3035;EPSG:32632;CRS:84", resolution="未标注", update_frequency="未知",
        format="PNG", auth="无", api_key_required="否", registration_required="否",
        free="是", commercial_use="未知", redistribution="未知", attribution="AdB Po",
        need_no_reg="是", need_no_key="是", is_free="是",
        support_api="是", support_spatial_query="未知", support_temporal_query="未知",
        support_batch="未知", support_download="未知", support_geojson="否", support_json="否",
        is_vector="是", is_raster="是", is_realtime="否",
        global_coverage="否", region_coverage="是",
        status="已验证", verify_method="protocol-probe:strong", last_verified=TODAY,
        notes="GetCapabilities 返回 WMS_Capabilities(2026-10-07)；本轮单库图层最多的新条目(769)",
    ),
    # ---------- 专题纵深 ----------
    dict(
        service_id="R10-0010", service_name="北领地地质调查局 Geoscience Data WMS",
        country="澳大利亚", region="大洋洲", provider="Northern Territory Geological Survey",
        category="地质", service_type="WMS", protocol=W,
        official_url="https://geology.data.nt.gov.au/", service_url="https://geology.data.nt.gov.au/geoserver/wms?service=WMS&request=GetCapabilities",
        docs_url="https://geology.data.nt.gov.au/", layer_or_endpoint="geoserver/wms（5 组图层）",
        data_description="澳北区地质调查局地球科学数据 WMS：区域地质图、矿点、地球物理等专题组",
        spatial_coverage="澳大利亚北领地", temporal_coverage="静态",
        crs="EPSG:28352;EPSG:28353;EPSG:32752;EPSG:3857", resolution="未标注", update_frequency="未知",
        format="PNG", auth="无", api_key_required="否", registration_required="否",
        free="是", commercial_use="是", redistribution="是", attribution="NT Geological Survey",
        need_no_reg="是", need_no_key="是", is_free="是",
        support_api="是", support_spatial_query="未知", support_temporal_query="否",
        support_batch="未知", support_download="未知", support_geojson="否", support_json="否",
        is_vector="是", is_raster="是", is_realtime="否",
        global_coverage="否", region_coverage="是",
        status="已验证", verify_method="protocol-probe:strong", last_verified=TODAY,
        notes="GetCapabilities 返回 WMS_Capabilities(2026-10-07)，标题'Northern Territory Geological Survey - Geoscience Data WMS'",
    ),
    dict(
        service_id="R10-0011", service_name="英国地质调查局 BGS 1:50,000 详细地质 WMS",
        country="英国", region="欧洲", provider="British Geological Survey（BGS）",
        category="地质", service_type="WMS", protocol=W,
        official_url="https://www.bgs.ac.uk/", service_url="https://map.bgs.ac.uk/arcgis/services/BGS_Detailed_Geology/MapServer/WMSServer?request=GetCapabilities&service=WMS",
        docs_url="https://www.bgs.ac.uk/technologies/web-map-services-wms/geoindex-wms-services/",
        layer_or_endpoint="WMSServer（6 图层）",
        data_description="BGS 5 万分之一英国数字地质图 WMS：基岩地质、第四纪、人工堆积等图层，开放许可",
        spatial_coverage="英国", temporal_coverage="静态",
        crs="EPSG:27700;EPSG:4258;EPSG:4326;EPSG:3857", resolution="1:50,000", update_frequency="静态",
        format="PNG", auth="无", api_key_required="否", registration_required="否",
        free="是", commercial_use="是", redistribution="是", attribution="UKRI/BGS",
        need_no_reg="是", need_no_key="是", is_free="是",
        support_api="是", support_spatial_query="未知", support_temporal_query="否",
        support_batch="未知", support_download="未知", support_geojson="否", support_json="否",
        is_vector="是", is_raster="否", is_realtime="否",
        global_coverage="否", region_coverage="是",
        status="已验证", verify_method="protocol-probe:strong", last_verified=TODAY,
        notes="WMSServer GetCapabilities 返回 WMS_Capabilities(2026-10-07)，标题'BGS 50000 scale digital geology'",
    ),
    dict(
        service_id="R10-0012", service_name="FEMA GeoServer WMS（开放避难所等图层）",
        country="美国", region="北美", provider="FEMA（美国联邦应急管理署）",
        category="灾害", service_type="WMS", protocol=W,
        official_url="https://gis.fema.gov/geoserver/web/", service_url="https://gis.fema.gov/geoserver/wms?service=WMS&request=GetCapabilities",
        docs_url="https://gis.fema.gov/", layer_or_endpoint="geoserver/wms（1 图层 open_shelters_new）",
        data_description="FEMA 官方 GeoServer：目前公开 open_shelters_new（开放避难所）图层；国家洪水灾害图层见库内 THEME-0040（hazards.fema.gov）",
        spatial_coverage="美国", temporal_coverage="灾害期动态更新",
        crs="AUTO:42001-42004;AUTO:97001-97002", resolution="未标注", update_frequency="灾害事件驱动",
        format="PNG;GeoJSON", auth="无", api_key_required="否", registration_required="否",
        free="是", commercial_use="是", redistribution="是", attribution="FEMA",
        need_no_reg="是", need_no_key="是", is_free="是",
        support_api="是", support_spatial_query="未知", support_temporal_query="否",
        support_batch="未知", support_download="是", support_geojson="是", support_json="否",
        is_vector="是", is_raster="否", is_realtime="否",
        global_coverage="否", region_coverage="是",
        status="已验证", verify_method="protocol-probe:strong", last_verified=TODAY,
        notes="GetCapabilities 返回 WMS_Capabilities(2026-10-07)；当前仅 1 个公开命名图层，内容随灾害事件变化",
    ),
    dict(
        service_id="R10-0013", service_name="NOAA NCEP OpenGeo GeoServer WMS",
        country="美国", region="北美", provider="NOAA NCEP（美国国家环境预报中心）",
        category="气象", service_type="WMS", protocol=W,
        official_url="https://opengeo.ncep.noaa.gov/geoserver/www/index.html", service_url="https://opengeo.ncep.noaa.gov/geoserver/wms?service=WMS&request=GetCapabilities",
        docs_url="https://opengeo.ncep.noaa.gov/geoserver/www/index.html", layer_or_endpoint="geoserver/wms（940 图层）",
        data_description="NCEP 开放地理服务 GeoServer：行政边界、水文、陆地数据产品等 940 个图层，供 NDFD 等业务系统取图",
        spatial_coverage="美国为主（含北美）", temporal_coverage="业务持续更新",
        crs="EPSG:3857;EPSG:4269;EPSG:4326;CRS:84", resolution="未标注", update_frequency="持续更新",
        format="PNG", auth="无", api_key_required="否", registration_required="否",
        free="是", commercial_use="是", redistribution="是", attribution="NOAA NCEP",
        need_no_reg="是", need_no_key="是", is_free="是",
        support_api="是", support_spatial_query="未知", support_temporal_query="未知",
        support_batch="未知", support_download="未知", support_geojson="否", support_json="否",
        is_vector="是", is_raster="是", is_realtime="是",
        global_coverage="否", region_coverage="是",
        status="已验证", verify_method="protocol-probe:strong", last_verified=TODAY,
        notes="GetCapabilities 返回 WMS_Capabilities(2026-10-07)，940 图层——本轮图层最多的强命中",
    ),
    dict(
        service_id="R10-0014", service_name="澳大利亚气象局 BOM THREDDS 服务器",
        country="澳大利亚", region="大洋洲", provider="Bureau of Meteorology（澳大利亚气象局）",
        category="气象", service_type="时空目录", protocol="THREDDS",
        official_url="http://opendap.bom.gov.au:8080/", service_url="http://opendap.bom.gov.au:8080/thredds/catalog.html",
        docs_url="https://www.opendap.org/", layer_or_endpoint="thredds/catalog.html（THREDDS 5）",
        data_description="BOM 官方 OPeNDAP/THREDDS 服务器：气象模型场、降水、温度等 gridded 数据目录，支持 OPeNDAP/WMS/WCS 子集访问",
        spatial_coverage="澳大利亚及全球模式域", temporal_coverage="持续更新",
        crs="随数据集", resolution="未标注", update_frequency="持续更新",
        format="NetCDF;GRIB", auth="无", api_key_required="否", registration_required="否",
        free="是", commercial_use="未知", redistribution="未知", attribution="Australian BOM",
        need_no_reg="是", need_no_key="是", is_free="是",
        support_api="是", support_spatial_query="未知", support_temporal_query="是",
        support_batch="未知", support_download="是", support_geojson="否", support_json="否",
        is_vector="否", is_raster="是", is_realtime="是",
        global_coverage="否", region_coverage="是",
        status="已验证", verify_method="protocol-probe:strong", last_verified=TODAY,
        notes="thredds/catalog.html 返回 THREDDS 目录页(2026-10-07)；8080 端口，部分内网防火墙需放行",
    ),
    dict(
        service_id="R10-0015", service_name="SECOORA FACT Network ERDDAP",
        country="美国", region="北美", provider="SECOORA（美国东南海岸海洋观测区）FACT 网络",
        category="海洋", service_type="数据API", protocol="ERDDAP",
        official_url="https://erddap.factnetwork.secoora.org/", service_url="https://erddap.factnetwork.secoora.org/erddap/index.html",
        docs_url="https://erddap.factnetwork.secoora.org/erddap/index.html", layer_or_endpoint="/erddap/（search/tabledap/griddap/wms）",
        data_description="美国东南部海洋观测联盟(SECOORA) FACT 网络的 ERDDAP 服务器：沿岸海洋观测、动物遥测轨迹等数据集，标准 ERDDAP 协议访问",
        spatial_coverage="美国东南沿岸", temporal_coverage="持续更新",
        crs="EPSG:4326", resolution="未标注", update_frequency="持续更新",
        format="CSV;NetCDF;GeoJSON", auth="无", api_key_required="否", registration_required="否",
        free="是", commercial_use="是", redistribution="是", attribution="SECOORA FACT",
        need_no_reg="是", need_no_key="是", is_free="是",
        support_api="是", support_spatial_query="未知", support_temporal_query="是",
        support_batch="未知", support_download="是", support_geojson="是", support_json="是",
        is_vector="是", is_raster="是", is_realtime="是",
        global_coverage="否", region_coverage="是",
        status="已验证", verify_method="protocol-probe:weak", last_verified=TODAY,
        notes="ERDDAP 首页 200 且 search API 以规范 ERDDAP 格式应答(2026-10-07)；但 itemsPerPage 检索返回空集，无法枚举具体数据集，按 weak 收录",
    ),
    dict(
        service_id="R10-0016", service_name="NOAA CoastWatch ERDDAP（中大西洋节点）",
        country="美国", region="北美", provider="NOAA CoastWatch",
        category="海洋", service_type="数据API", protocol="ERDDAP",
        official_url="https://coastwatch.noaa.gov/", service_url="https://coastwatch.noaa.gov/erddap/index.html",
        docs_url="https://coastwatch.noaa.gov/erddap/index.html", layer_or_endpoint="/erddap/（search/tabledap/griddap/wms）",
        data_description="NOAA CoastWatch 中大西洋节点 ERDDAP：卫星海表温度、叶绿素、水色等海洋遥感产品，标准 ERDDAP 协议",
        spatial_coverage="美国沿岸/大西洋", temporal_coverage="持续更新",
        crs="EPSG:4326", resolution="未标注", update_frequency="持续更新",
        format="CSV;NetCDF;PNG", auth="无", api_key_required="否", registration_required="否",
        free="是", commercial_use="是", redistribution="是", attribution="NOAA CoastWatch",
        need_no_reg="是", need_no_key="是", is_free="是",
        support_api="是", support_spatial_query="未知", support_temporal_query="是",
        support_batch="未知", support_download="是", support_geojson="是", support_json="是",
        is_vector="否", is_raster="是", is_realtime="是",
        global_coverage="否", region_coverage="是",
        status="已验证", verify_method="protocol-probe:weak", last_verified=TODAY,
        notes="ERDDAP search API 以规范协议应答(2026-10-07)，但示例检索返回空集，未逐数据集验证，按 weak 收录",
    ),
    dict(
        service_id="R10-0017", service_name="IOOS Sensors ERDDAP",
        country="美国", region="北美", provider="IOOS（美国综合海洋观测系统）",
        category="海洋", service_type="数据API", protocol="ERDDAP",
        official_url="https://erddap.sensors.ioos.us/", service_url="https://erddap.sensors.ioos.us/erddap/index.html",
        docs_url="https://erddap.sensors.ioos.us/erddap/index.html", layer_or_endpoint="/erddap/（search/tabledap/griddap/wms）",
        data_description="IOOS 官方传感器 ERDDAP：全国浮标、验潮站、漂流浮标等实时海洋传感器时间序列，标准 ERDDAP 协议",
        spatial_coverage="美国沿岸", temporal_coverage="实时",
        crs="EPSG:4326", resolution="未标注", update_frequency="实时",
        format="CSV;NetCDF;JSON", auth="无", api_key_required="否", registration_required="否",
        free="是", commercial_use="是", redistribution="是", attribution="IOOS",
        need_no_reg="是", need_no_key="是", is_free="是",
        support_api="是", support_spatial_query="未知", support_temporal_query="是",
        support_batch="未知", support_download="是", support_geojson="是", support_json="是",
        is_vector="是", is_raster="否", is_realtime="是",
        global_coverage="否", region_coverage="是",
        status="已验证", verify_method="protocol-probe:weak", last_verified=TODAY,
        notes="ERDDAP search API 以规范协议应答(2026-10-07)，示例检索空集，按 weak 收录",
    ),
    dict(
        service_id="R10-0018", service_name="NOAA SWFSC CoastWatch ERDDAP（西海岸）",
        country="美国", region="北美", provider="NOAA SWFSC / CoastWatch West Coast Node",
        category="海洋", service_type="数据API", protocol="ERDDAP",
        official_url="https://coastwatch.pfeg.noaa.gov/", service_url="https://coastwatch.pfeg.noaa.gov/erddap/index.html",
        docs_url="https://coastwatch.pfeg.noaa.gov/erddap/index.html", layer_or_endpoint="/erddap/（search/tabledap/griddap/wms）",
        data_description="NOAA 西海岸 CoastWatch 节点(原 PFEG) ERDDAP：加州沿岸卫星海洋学、渔业环境数据集，长期运营的老牌节点",
        spatial_coverage="美国西海岸/东北太平洋", temporal_coverage="持续更新",
        crs="EPSG:4326", resolution="未标注", update_frequency="持续更新",
        format="CSV;NetCDF;PNG", auth="无", api_key_required="否", registration_required="否",
        free="是", commercial_use="是", redistribution="是", attribution="NOAA SWFSC",
        need_no_reg="是", need_no_key="是", is_free="是",
        support_api="是", support_spatial_query="未知", support_temporal_query="是",
        support_batch="未知", support_download="是", support_geojson="是", support_json="是",
        is_vector="否", is_raster="是", is_realtime="是",
        global_coverage="否", region_coverage="是",
        status="已验证", verify_method="protocol-probe:weak", last_verified=TODAY,
        notes="ERDDAP search API 以规范协议应答(2026-10-07)，示例检索空集，按 weak 收录",
    ),
    dict(
        service_id="R10-0041", service_name="GLIMS 全球冰川数据库 WMS（含 RGI 7.0）",
        country="美国", region="全球(极地为主)", provider="NSIDC / GLIMS Consortium",
        category="冰川", service_type="WMS", protocol=W,
        official_url="https://www.glims.org/", service_url="https://www.glims.org/geoserver/wms?service=WMS&request=GetCapabilities",
        docs_url="https://www.glims.org/maps/glims", layer_or_endpoint="geoserver/wms（54 图层）",
        data_description="全球陆地冰空间测量计划(GLIMS)官方 GeoServer：全球冰川轮廓、GLIMS 分区、RGI 7.0 各区域冰川栅格、观测点与机构图层",
        spatial_coverage="全球冰川区", temporal_coverage="持续更新",
        crs="AUTO:42001-42004;CRS:84", resolution="未标注", update_frequency="持续更新",
        format="PNG;Shapefile", auth="无", api_key_required="否", registration_required="否",
        free="是", commercial_use="是", redistribution="是", attribution="GLIMS/NSIDC",
        need_no_reg="是", need_no_key="是", is_free="是",
        support_api="是", support_spatial_query="未知", support_temporal_query="未知",
        support_batch="未知", support_download="是", support_geojson="否", support_json="否",
        is_vector="是", is_raster="否", is_realtime="否",
        global_coverage="是", region_coverage="否",
        status="已验证", verify_method="protocol-probe:strong", last_verified=TODAY,
        notes="GetCapabilities 返回 WMS_Capabilities(2026-10-07)，54 图层含 GLIMS:RGI70 与 RGI2000 v7.0 各分区；冰川类目此前仅 1 条，本条补强",
    ),
]

GENERIC_DEFAULTS = dict(
    caching_allowed="未知", rate_limit="未知", query_limit="未知", download_limit="未知",
    pagination="未知", batch_query="未知", commercial_ok="未知", cache_ok="未知", redistribute_ok="未知",
)

conn = sqlite3.connect("gis_services.db")
cur = conn.cursor()
cols = [r[1] for r in cur.execute("PRAGMA table_info(master)")]
inserted = []
for row in NEW_ROWS:
    from urllib.parse import urlsplit
    p = urlsplit(row["service_url"])
    root = f"{p.scheme}://{p.netloc}".lower()
    dup = cur.execute(
        "SELECT service_id FROM master WHERE LOWER(service_url) LIKE ? OR LOWER(official_url) LIKE ?",
        (root + "/%", root + "/%")).fetchone()
    if dup:
        print(f"查重跳过 {row['service_id']} {row['service_name']} -> 已有 {dup[0]}")
        continue
    values = {c: None for c in cols}
    for k, v in row.items():
        if k in cols:
            values[k] = v
    for k, v in GENERIC_DEFAULTS.items():
        values.setdefault(k, v)
    placeholders = ",".join("?" for _ in cols)
    cur.execute(f"INSERT INTO master ({','.join(cols)}) VALUES ({placeholders})",
                [values[c] for c in cols])
    inserted.append(row["service_id"])

conn.commit()
n = cur.execute("select count(*) from master").fetchone()[0]
print(f"插入 {len(inserted)} 条，master 总数 -> {n}")
for r in cur.execute("select service_id,service_name,status,verify_method from master where service_id like 'R10-%'"):
    print(" ", r)
conn.close()
